// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://keyitpwqzgyaqbtisfgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtleWl0cHdxemd5YXFidGlzZmd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNTgwODQsImV4cCI6MjA3NDYzNDA4NH0.k4kfHeICWzK0KB3n3eJuWPiDdlP1x5MPM1a38L2xIWY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});